# Generated by Django 3.2.16 on 2025-09-30 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                upload_to='posts_images',
                verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Снимите галочку, чтобы скрыть публикацию.',
                verbose_name='Опубликовано'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('text',
                 models.TextField(
                     verbose_name='Текст комментария')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True)),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comments',
                     to=settings.AUTH_USER_MODEL)),
                ('post',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comments',
                     to='blog.post')),
            ],
        ),
    ]
